### ISSUE TITLE
Provider does not load config values

### ISSUE THREAD

**Issue by mattiadevivo** [pulumi/pulumi-gitlab#279] opened 2023-05-24 09:43 UTC
### What happened?

Config values `gitlab:token` and `gitlab:base_url` are not correctly loaded by the Provider.

I tried by putting the configuration values both in `Pulumi.yaml` and `Pulumi.dev.yaml` files but none of them worked, the only way I got it working is to explicitly configure the provider in the code.

### Expected Behavior

To have the GitLab provider configured with the values provided in the `Pulumi.<stack>.yaml` file.

### Steps to reproduce

Set 
```yaml
gitlab:base_url: https://<gitlab-host>/api/v4/
gitlab:token:
    secure: <encrypted-token>
```
in your `Pulumi.<stack>.yaml` file.

Run `pulumi up` and you will get the following error:
```
error: Failed to create GitLab Client from provider configuration: The provider failed to create a new GitLab Client from the given configuration: GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}
```

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.102.0
azuread       5.37.0
flux          0.22.2
gcp           6.56.0
gitlab        5.0.2
kubernetes    3.27.1
nodejs        unknown
random        4.13.0
tls           4.10.0

Host     
OS       darwin
Version  12.3
Arch     arm64

This project is written in nodejs: executable='/Users/mattia.devivo@igenius.ai/.nvm/versions/node/v18.13.0/bin/node' version='v18.13.0'

Current Stack: organization/infrastructure/dev

TYPE                                                         URN
pulumi:pulumi:Stack                                          urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev
custom:gcp:GcpServiceAccount                                 urn:pulumi:dev::infrastructure::custom:gcp:GcpServiceAccount::gcp-service-account
pulumi:providers:flux                                        urn:pulumi:dev::infrastructure::pulumi:providers:flux::default_0_22_2
pulumi:providers:gitlab                                      urn:pulumi:dev::infrastructure::pulumi:providers:gitlab::gitlab-provider
pulumi:providers:random                                      urn:pulumi:dev::infrastructure::pulumi:providers:random::default_4_13_0
random:index/randomPassword:RandomPassword                   urn:pulumi:dev::infrastructure::random:index/randomPassword:RandomPassword::postgres-password
pulumi:providers:tls                                         urn:pulumi:dev::infrastructure::pulumi:providers:tls::default_4_10_0
pulumi:providers:gcp                                         urn:pulumi:dev::infrastructure::pulumi:providers:gcp::default_6_56_0
tls:index/privateKey:PrivateKey                              urn:pulumi:dev::infrastructure::tls:index/privateKey:PrivateKey::bastion-ssh-key
pulumi:providers:azure-native                                urn:pulumi:dev::infrastructure::pulumi:providers:azure-native::default_1_102_0
gcp:serviceAccount/account:Account                           urn:pulumi:dev::infrastructure::gcp:serviceAccount/account:Account::aks-service-account
azure-native:resources:ResourceGroup                         urn:pulumi:dev::infrastructure::azure-native:resources:ResourceGroup::crystal-dev
azure-native:resources:ResourceGroup                         urn:pulumi:dev::infrastructure::azure-native:resources:ResourceGroup::crystal-aks-dev
pulumi:providers:kubernetes                                  urn:pulumi:dev::infrastructure::pulumi:providers:kubernetes::default_3_27_1
azure-native:operationalinsights:Workspace                   urn:pulumi:dev::infrastructure::azure-native:operationalinsights:Workspace::aks-dev-logsanalytics
gcp:serviceAccount/key:Key                                   urn:pulumi:dev::infrastructure::gcp:serviceAccount/key:Key::aks-service-account-key
azure-native:network:PrivateZone                             urn:pulumi:dev::infrastructure::azure-native:network:PrivateZone::pgsql-private-zone
azure-native:network:VirtualNetwork                          urn:pulumi:dev::infrastructure::azure-native:network:VirtualNetwork::crystal-dev
azure-native:network:PublicIPAddress                         urn:pulumi:dev::infrastructure::azure-native:network:PublicIPAddress::bastion-ip
azure-native:network:VirtualNetworkLink                      urn:pulumi:dev::infrastructure::azure-native:network:VirtualNetworkLink::vnet-dns-link
azure-native:network:Subnet                                  urn:pulumi:dev::infrastructure::azure-native:network:Subnet::subnet-1
azure-native:network:Subnet                                  urn:pulumi:dev::infrastructure::azure-native:network:Subnet::subnet-2
azure-native:network:Subnet                                  urn:pulumi:dev::infrastructure::azure-native:network:Subnet::subnet-0
azure-native:dbforpostgresql/v20221201:Server                urn:pulumi:dev::infrastructure::azure-native:dbforpostgresql/v20221201:Server::crystal-dev
azure-native:network:NetworkInterface                        urn:pulumi:dev::infrastructure::azure-native:network:NetworkInterface::bastion-nic
azure-native:containerservice:ManagedCluster                 urn:pulumi:dev::infrastructure::azure-native:containerservice:ManagedCluster::crystal-dev
azure-native:compute:VirtualMachine                          urn:pulumi:dev::infrastructure::azure-native:compute:VirtualMachine::bastion
pulumi:providers:kubernetes                                  urn:pulumi:dev::infrastructure::pulumi:providers:kubernetes::k8s-provider
custom:flux:Flux                                             urn:pulumi:dev::infrastructure::custom:flux:Flux::flux
kubernetes:yaml:ConfigGroup                                  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup::flux-sync
kubernetes:yaml:ConfigGroup                                  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup::flux-install
tls:index/privateKey:PrivateKey                              urn:pulumi:dev::infrastructure::custom:flux:Flux$tls:index/privateKey:PrivateKey::flux-ssh-key
gitlab:index/repositoryFile:RepositoryFile                   urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/repositoryFile:RepositoryFile::flux-sync
gitlab:index/repositoryFile:RepositoryFile                   urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/repositoryFile:RepositoryFile::kustomize
gitlab:index/repositoryFile:RepositoryFile                   urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/repositoryFile:RepositoryFile::flux-install
kubernetes:core/v1:Namespace                                 urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Namespace::flux-system
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/helm-controller
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/notification-controller
kubernetes:networking.k8s.io/v1:NetworkPolicy                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:networking.k8s.io/v1:NetworkPolicy::flux-system/allow-scraping
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/source-controller
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/kustomize-controller
kubernetes:core/v1:Service                                   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service::flux-system/webhook-receiver
kubernetes:networking.k8s.io/v1:NetworkPolicy                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:networking.k8s.io/v1:NetworkPolicy::flux-system/allow-webhooks
kubernetes:networking.k8s.io/v1:NetworkPolicy                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:networking.k8s.io/v1:NetworkPolicy::flux-system/allow-egress
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole          urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::crd-controller-flux-system
kubernetes:core/v1:Service                                   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service::flux-system/source-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::providers.notification.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::helmrepositories.source.toolkit.fluxcd.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cluster-reconciler-flux-system
kubernetes:core/v1:Service                                   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service::flux-system/notification-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::alerts.notification.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::buckets.source.toolkit.fluxcd.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::crd-controller-flux-system
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::ocirepositories.source.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::receivers.notification.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::helmreleases.helm.toolkit.fluxcd.io
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/notification-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::helmcharts.source.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::gitrepositories.source.toolkit.fluxcd.io
gitlab:index/deployKey:DeployKey                             urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/deployKey:DeployKey::flux-key
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::kustomizations.kustomize.toolkit.fluxcd.io
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/source-controller
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/helm-controller
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/kustomize-controller
kubernetes:core/v1:Secret                                    urn:pulumi:dev::infrastructure::kubernetes:core/v1:Secret::docker-secret

Found no pending operations associated with dev

Backend        
Name           mac-pro-mattia
URL            s3://crystal-azure-pulumi
User           mattia.devivo@igenius.ai
Organizations  

Dependencies:
NAME                  VERSION
@types/node           16.18.27
@worawat/flux         0.22.2
@pulumi/azuread       5.37.0
@pulumi/tls           4.10.0
@pulumi/gitlab        5.0.2
@pulumi/kubernetes    3.27.1
@pulumi/pulumi        3.66.0
@pulumi/random        4.13.0
@pulumi/azure-native  1.102.0
@pulumi/gcp           6.56.0

Pulumi locates its logs in /var/folders/81/r9pvsdlx2n1378qhpf7hjg_40000gp/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-05-24 13:31
Hi @mattiadevivo thanks for reporting this issue, it's quite concerning since it looks to affect provider configuration area similarly to the recently closed https://github.com/pulumi/pulumi-gitlab/issues/273 

We currently don't have access to a GitLab enterprise account for testing but I've tested this program and was not able to reproduce:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as gitlab from "@pulumi/gitlab";

const project = new gitlab.Project("example-project", {
    description: "example project created by Pulumi",
    visibilityLevel: "public",
})

export const projectName = project.name
```

```
pulumi config set gitlab:base_url https://gitlab.com/
pulumi config set gitlab:token $GITLAB_TOKEN --secret
pulumi up --yes
cat Pulumi.dev.yaml                                                                                                                                                       ~/tmp/2023/05/gitlab-279
config:
  gitlab:base_url: https://gitlab.com
  gitlab:token:
    secure: <redacted>
```

This succeeds for me on `pulumi up`.

```
CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
gitlab  5.0.2
nodejs  unknown

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/.nix-profile/bin/node' version='v18.12.1'

Current Stack: t0yv0/gitlab-279/dev

TYPE                          URN
pulumi:pulumi:Stack           urn:pulumi:dev::gitlab-279::pulumi:pulumi:Stack::gitlab-279-dev
pulumi:providers:gitlab       urn:pulumi:dev::gitlab-279::pulumi:providers:gitlab::default_5_0_2
gitlab:index/project:Project  urn:pulumi:dev::gitlab-279::gitlab:index/project:Project::example-project


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME            VERSION
@types/node     16.18.32
@pulumi/gitlab  5.0.2
@pulumi/pulumi  3.68.0

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

Could you try resetting the tokens with `pulumi config set gitlab:token "$MY_TOKEN" --secret` to ensure it's set correctly?

Does the problem persist when downgrading this provider to 4.10.0?

**Comment by mattiadevivo** [comment] 2023-05-25 08:22
Hi, I tried resetting the token with the `pulumi config set gitlab:token "$MY_TOKEN" --secret` command but it didn't fix the problem.

The problem disappeared by downgrading the provider to version 4.10.0.

**Comment by qerub** [comment] 2023-06-12 12:45
I've also run into this issue.

@t0yv0: You might have been unable to reproduce this since you configured `gitlab:base_url` to https://gitlab.com/ (which is also the default value) and seem to have had the environment variable `GITLAB_TOKEN` defined (which Pulumi reads).

Configuring through environment variables i.e. GITLAB_BASE_URL and GITLAB_TOKEN still works so I use that as a workaround for now.

**Comment by onlynone** [comment] 2023-06-15 04:02
It appears that the config value on the pulumi side of things has changed from `gitlab:base_url` to `gitlab:baseUrl`. If I do the following:

```
pulumi config rm gitlab:base_url
pulumi config set gitlab:baseUrl 'https://<gitlab-host>/api/v4/'
```

Then it works for me. I'm not sure if the other config values with underscores (like `cacert_file`) are also affected.

**Comment by mattiadevivo** [comment] 2023-06-15 08:13
> It appears that the config value on the pulumi side of things has changed from `gitlab:base_url` to `gitlab:baseUrl`. If I do the following:
> 
> ```
> pulumi config rm gitlab:base_url
> pulumi config set gitlab:baseUrl 'https://<gitlab-host>/api/v4/'
> ```
> 
> Then it works for me. I'm not sure if the other config values with underscores (like `cacert_file`) are also affected.

I don't know If I looked at the right file but it seems that @onlynone  is right: https://github.com/pulumi/pulumi-gitlab/blob/master/provider/cmd/pulumi-resource-gitlab/schema.json

**Comment by mattiadevivo** [comment] 2023-06-15 08:50
@t0yv0  I just opened a PR #291

**Comment by t0yv0** [comment] 2023-06-22 21:26
@mattiadevivo I've just checked this again using the 6.0.0 version of the provider. 

```
pulumi config rm gitlab:base_url
pulumi config set gitlab:base_url 'https://gitlab.com/api/v4/'
pulumi config set gitlab:base_url 'https://gitlab-bad.com/api/v4/'
pulumi config rm gitlab:baseUrl
pulumi config set gitlab:baseUrl 'https://gitlab.com/api/v4/'
pulumi config set gitlab:baseUrl 'https://gitlab-bad.com/api/v4/'
```

In both cases Pulumi responded the same - the correct URL works but the bad URL yields:

```
    error: 1 error occurred:
        * Get "https://gitlab40.com/api/v4/user": dial tcp: lookup gitlab-bad.com: no such host
```

So it seems to me that it's reading baseUrl and base_url exactly the same way.

I've checked 5.0.2 version again and I'm getting the same results. I believe it's consulting both spellings. 

Unfortunately I do not have a custom GitLab URL to easily test against.

**Comment by onlynone** [comment] 2023-06-22 21:35
What's with the `gitlab40.com` domain in the GET request, but the error being about `gitlab-bad.com` ? Is it possible that you've got `GITLAB_BASE_URL` in your environment?

**Comment by t0yv0** [comment] 2023-06-22 22:01
Sorry that was just a typo. It's consistent. I've got empty `env | grep GITLAB`.

**Comment by t0yv0** [comment] 2023-06-22 22:28
Accepted the PR to fix the README with gitlab:baseUrl but closing as "can't reproduce" for now. I've also checked that I can get preview to work with bad `base_url` by setting either `pulumi config set gitlab:earlyAuthCheck false` or `pulumi config set gitlab:early_auth_check false` so the provider clearly is responding to both spellings.. The key concern here was that the bridge regressed in how these values are passed through to the underlying TF provider, but it appears that these values make it all the way in either spelling.

**Closed** 2023-06-22 22:28 UTC
Labels: resolution/no-repro, kind/bug
